### ISSUE TITLE
recover local party data from remote parties

### ISSUE THREAD

**Issue by RobinLevesque24** [Safeheron/multi-party-sig-cpp#13]
How can one recover a user's local party data with threshold + 1 security shares?
For example, if I have three parties, can I recover my local party data through the other two remote parties? If possible, could you provide code references?

**Comment by sword03** [comment]
It depends on the threshold scheme. If it's 3-3, it's impossible; if it's 2-3, then it's possible. The relevant share recovery algorithm will be announced soon.

**Comment by RobinLevesque24** [comment]
it's create,i am looking forward the share recovery algorithm!!!

sword03 ***@***.***> 于2024年1月3日周三 18:19写道：
