### ISSUE TITLE
fail to debug

### ISSUE THREAD

**Issue by mstc-xqp** [Safeheron/multi-party-sig-cpp#14]
![Screenshot from 2024-01-12 21-59-10](https://github.com/Safeheron/multi-party-sig-cpp/assets/19384581/6670767f-8097-43ad-83a4-11030e3bbcce)
The project can run but can not stop 通常意味着IDE已经识别到了断点，但这个断点当前未被激活，

**Comment by sword03** [comment]
You have to build it in debug model.
