### ISSUE TITLE
is it safe to keep gamma and k unchanged?

### ISSUE THREAD

**Issue by nealsun** [Safeheron/multi-party-sig-cpp#15]
do i need to generate gamma and k in every individual sign process?

**Comment by sword03** [comment]
Yes. If you keep gamma and k the same, then the attacker can compute the secret key. refer to https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm

![image](https://github.com/Safeheron/multi-party-sig-cpp/assets/13059372/123ddbc6-e6ae-47ef-99b5-f40b6817e3a1)

For security, each execution of MPC protocol should use different random numbers.
