### ISSUE TITLE
mta.proto missing

### ISSUE THREAD

**Issue by eto-ldittrich** [Safeheron/multi-party-sig-cpp#16]
proto/gg18/sign.proto and proto/gg20/sign.proto import a mta.proto file. Where can this file be found?

**Comment by sword03** [comment]
Just remove this line of code because "mta.proto" is never used here.

import "mta.proto";

**Comment by sword03** [comment]
Thank you for your reminder. The Proto file has been updated, refer to the commit:

https://github.com/Safeheron/multi-party-sig-cpp/commit/807a7a1253936b521d54745e6e909261323b52a4
