### ISSUE TITLE
security issue：public key X is not included in MtAwc‘s challenge calculation

### ISSUE THREAD

**Issue by a7853z** [Safeheron/multi-party-sig-cpp#18]
ZKP verifier's challenge's calculation should include all public information. Thereby,  `statement.X_` should be included to calculate `e`. However, it is missing in the code. 

https://github.com/Safeheron/crypto-zkp-cpp/blob/f8cb86b6e1abb3fdc3df3cd26a30567755c85c7b/src/crypto-zkp/pail/pail_aff_group_ele_range_proof_v1.cpp#L71C1-L92C6

On the other hand, in binance tss-lib's MtAwc , this information is included to calculate the `e`.
https://github.com/bnb-chain/tss-lib/blob/master/crypto/mta/proofs.go#L102-L112

**Comment by sword03** [comment]
Hello, you found the wrong repository path, which is no longer maintained.

Please refer to the latest repository [safeheron-crypto-suites-cpp](https://github.com/Safeheron/safeheron-crypto-suites-cpp) and here is the zk proof: 

https://github.com/Safeheron/safeheron-crypto-suites-cpp/blob/main/src/crypto-suites/crypto-zkp/pail/pail_aff_group_ele_range_proof_v1.cpp. 

The statement.X is already included in the calculation of e in the zero-knowledge proof.

Tips: I have updated the documentation to avoid potential misunderstandings:  https://github.com/Safeheron/safeheron-crypto-suites-cpp/commit/ca3f84fe63a145ced14fb490136282718eea1adc
