### ISSUE TITLE
Undefined symbols for architecture arm64 when Make

### ISSUE THREAD

**Issue by maweis1981** [Safeheron/multi-party-sig-cpp#8]
`[ 73%] Linking CXX shared library libMultiPartyEcdsa.dylib
Undefined symbols for architecture arm64:
  "safeheron::multi_party_ecdsa::gg18::sign::MtA_Step1(safeheron::bignum::BN&, safeheron::pail::PailPubKey const&, safeheron::bignum::BN const&, safeheron::bignum::BN const&)", referenced from:
      safeheron::multi_party_ecdsa::gg20::sign::Round0::ComputeVerify() in round0.cpp.o
  "safeheron::multi_party_ecdsa::gg18::sign::MtA_Step2(safeheron::bignum::BN&, safeheron::bignum::BN&, safeheron::pail::PailPubKey const&, safeheron::bignum::BN const&, safeheron::bignum::BN const&, safeheron::bignum::BN const&, safeheron::bignum::BN const&, safeheron::bignum::BN const&)", referenced from:
      safeheron::multi_party_ecdsa::gg20::sign::Round1::ComputeVerify() in round1.cpp.o
  "safeheron::multi_party_ecdsa::gg18::sign::MtA_Step3(safeheron::bignum::BN&, safeheron::bignum::BN const&, safeheron::pail::PailPrivKey const&, safeheron::bignum::BN const&)", referenced from:
      safeheron::multi_party_ecdsa::gg20::sign::Round2::ComputeVerify() in round2.cpp.o
  "safeheron::multi_party_ecdsa::gg18::SignKey::FromBase64(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      safeheron::multi_party_ecdsa::gg20::sign::Context::CreateContext(safeheron::multi_party_ecdsa::gg20::sign::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, safeheron::bignum::BN const&) in context.cpp.o
  "safeheron::multi_party_ecdsa::gg18::SignKey::get_remote_party_pos(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) const", referenced from:
      safeheron::multi_party_ecdsa::gg20::sign::Round1::ParseMsg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round1.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round1::ReceiveVerify(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round1.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round2::ParseMsg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round2.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round2::ReceiveVerify(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round2.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round3::ParseMsg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round3.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round3::ReceiveVerify(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round3.cpp.o
      safeheron::multi_party_ecdsa::gg20::sign::Round4::ParseMsg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in round4.cpp.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libMultiPartyEcdsa.dylib] Error 1
make[1]: *** [CMakeFiles/MultiPartyEcdsa.dir/all] Error 2
make: *** [all] Error 2`

**Comment by Linode07** [comment]
+1.

**Comment by sword03** [comment]
You can try the latest version of the library.  If you have any more questions, you can ask me.
